### PR TITLE
Fix issue with null converter

### LINKED ISSUE #16: NullConverter not a class in rspec 3.3.0-3.3.2
Getting this error when running with rspec 3.3.0 and rspec-legacy_formatters 1.0.0:
```
          TypeError:
            NullConverter is not a class
          # ./vendor/bundle/ruby/2.2.0/gems/rspec-legacy_formatters-1.0.0/lib/rspec/legacy_formatters/snippet_extractor.rb:8:in `<class:SnippetExtractor>'
```

In rspec-core 3.3.0-3.3.2, the NullConverter class has changed to a module.

### PR DESCRIPTION
**Pull request by JonRowe**
Don't redefine null converter if it already exists, and define it appropriately for different RSpec versions. Fixes #16

### CODE REVIEW

**Comment by JonRowe** [comment]
Anyone care to review @rspec/rspec ?

**Comment by myronmarston** [comment]
Looks reasonable.  Have you tested this on multiple RSpec versions?

**Comment by JonRowe** [comment]
Not directly, and I think @yujinakayama's changes to snippet extractor will affect this again when released, but I did check the code history for the changes to this constant

**Comment by myronmarston** [comment]
LGTM

**Pull request merged**
